# Generated by Django 3.1.5 on 2021-01-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=10)),
                ('start_date', models.FloatField()),
                ('end_date', models.FloatField()),
                ('timezone', models.CharField(max_length=10)),
            ],
        ),
    ]
