# Generated by Django 3.1.5 on 2021-01-22 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurlar',
            old_name='doviz_ismi',
            new_name='kur_name',
        ),
        migrations.RemoveField(
            model_name='kurlar',
            name='alis',
        ),
        migrations.RemoveField(
            model_name='kurlar',
            name='fark',
        ),
        migrations.RemoveField(
            model_name='kurlar',
            name='kur_kodu',
        ),
        migrations.RemoveField(
            model_name='kurlar',
            name='satis',
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=10)),
                ('session_start', models.FloatField()),
                ('session_end', models.FloatField()),
                ('speaker', models.CharField(max_length=10)),
                ('Events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.events')),
            ],
        ),
    ]
