# Generated by Django 3.1.5 on 2021-01-22 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210122_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessions',
            options={'ordering': ['session_name']},
        ),
        migrations.RenameField(
            model_name='sessions',
            old_name='Events',
            new_name='events',
        ),
    ]
