# Generated by Django 3.1.5 on 2021-01-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210122_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='events',
        ),
        migrations.AddField(
            model_name='sessions',
            name='session_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
