# Generated by Django 3.1.5 on 2021-01-22 04:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20210122_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='events',
            field=models.ForeignKey(default=1., on_delete=django.db.models.deletion.CASCADE, to='API.events'),
            preserve_default=False,
        ),
    ]
